version: "3.4"

services:
  postgres:
    image: postgres:12
    ports:
      - "${TYPEORM_PORT-5432}:5432"
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}