apiVersion: apps/v1
kind: Deployment
metadata:
  name: starknet-archive
spec:
  selector:
    matchLabels:
      app: starknet-archive
  template:
    metadata:
      labels:
        app: starknet-archive
    spec:
      containers:
      - name: starknet-archive
        image: {{ .Values.image }}
        env:
        - name: "TYPEORM_PASSWORD"
          value: {{ .Values.typeorm_password }}
{{ toYaml .Values.env | indent 8 }}
        resources: 
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        # ports:
        # - containerPort: 5000
