apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        env:
        - name: "TYPEORM_PASSWORD"
          value: {{ .Values.typeorm_password }}
        - name: "TYPEORM_DATABASE"
          value: {{ .Values.typeorm_database }}
{{ toYaml .Values.env | indent 8 }}
        resources: 
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "100Mi"
            cpu: "100m"
