name: Build to ECR and deploy to EKS

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to ECR
      id: build
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}//starknet-archive/${{ secrets.IMAGE_TAG }}"
        echo "Pushing image to ECR"
        docker push ${{ steps.login-ecr.outputs.registry }}//starknet-archive/${{ secrets.IMAGE_TAG }}
        echo "::set-output name=image::${{ steps.login-ecr.outputs.registry }}//starknet-archive/${{ secrets.IMAGE_TAG }}"

    - name: Deploy to EKS
      uses: tensor-hq/eksctl-helm-action@0.1.0
      with:
        eks_cluster: dev-eks-starknet-indexer
        # plugins: "https://github.com/jkroepke/helm-secrets"
        command: |-
          env
          helm upgrade starknet-archive ./helmchart/ --install --create-namespace --namespace dev --set typeorm_password=${{ secrets.TYPEORM_PASSWORD }} --set image=${{ steps.build.image }}
          kubectl get pods