name: Deploy to EKS

#on:
#  push:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to EKS with helm upgrade
      uses: tensor-hq/eksctl-helm-action@0.1.0
      with:
        eks_cluster: dev-eks-starknet-indexer
        # plugins: "https://github.com/jkroepke/helm-secrets"
        command: |-
          env
          helm upgrade starknet-archive ./helmchart/ --install --create-namespace --namespace dev --set typeorm_password=${{ secrets.TYPEORM_PASSWORD }} --set image=${{ secrets.IMAGE }}
          kubectl get pods