name: Deploy Archive to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: helm deploy
        uses: tensor-hq/eksctl-helm-action@0.1.0
        with:
          eks_cluster: dev-eks-starknet-indexer
          # plugins: "https://github.com/jkroepke/helm-secrets"
          command: |-
            env
            helm upgrade starknet-archive-deployment ./helmchart/ --install -f ./helmchart/values.yaml --create-namespace -n dev --set rds_password=${{ secrets.PASSWORD_DATABASE_RDS }}
            kubectl get pods